"""Add delivered_at and cancelled_at to Order model

Revision ID: 174d64b7be1f
Revises: 99cfc90ebe5b
Create Date: 2024-12-23 02:56:26.065898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174d64b7be1f'
down_revision = '99cfc90ebe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('delivered_at')

    # ### end Alembic commands ###
