"""Add total_amount to Order model

Revision ID: 363c7bf85d37
Revises: afa2d5800d62
Create Date: 2024-12-23 02:04:49.915760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363c7bf85d37'
down_revision = 'afa2d5800d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
