"""Add payment_method to Order model

Revision ID: 99cfc90ebe5b
Revises: 363c7bf85d37
Create Date: 2024-12-23 02:13:29.715149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cfc90ebe5b'
down_revision = '363c7bf85d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), server_default='cash', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
